name: aws-cdk

on:
  push:
    paths:
      - 'aws-cdk/**'
      - '!aws-cdk/README.md'
      - '!aws-cdk/.dockerignore'
    branches:
      - master
  workflow_run:
    types:
      - completed
    workflows:
      - aws-node18
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: isaacsancheza/workflows/.github/workflows/build-and-push.yaml@master
    with:
      tag: aws-cdk
      context: aws-cdk
