name: aws-python3.8

on:
  push:
    paths:
      - aws-python3.8/**
    branches:
      - master
  workflow_run:
    types:
      - completed
    workflows:
      - python3.8
    branches:
      - master

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push.yaml
    with:
      tag: aws-python3.8
      context: aws-python3.8
