name: aws-node18

on:
  push:
    paths:
      - 'aws-node18/**'
      - '!aws-node18/README.md'
      - '!aws-node18/.dockerignore'
    branches:
      - master
  workflow_run:
    types:
      - completed
    workflows:
      - aws-python3.11
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: isaacsancheza/workflows/.github/workflows/build-and-push.yaml@master
    with:
      tag: aws-node18
      context: aws-node18
