name: aws-python3.11

on:
  push:
    paths:
      - 'aws-python3.11/**'
      - '!aws-python3.11/README.md'
      - '!aws-python3.11/.dockerignore'
    branches:
      - master
  workflow_run:
    types:
      - completed
    workflows:
      - python3.11
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push.yaml
    with:
      tag: aws-python3.11
      context: aws-python3.11
