name: debian

on:
  push:
    paths:
      - 'debian/**'
      - '!debian/README.md'
      - '!debian/.dockerignore'
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: isaacsancheza/workflows/.github/workflows/build-and-push.yaml@master
    with:
      tag: debian
      context: debian
