name: debian

on:
  push:
    paths:
      - debian/**
      - !debian/README.md
      - !debian/.dockerignore
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push.yaml
    with:
      tag: debian
      context: debian
