name: node18

on:
  push:
    paths:
      - node18/**
    branches:
      - master
  workflow_run:
    types:
      - completed
    workflows:
      - debian
    branches:
      - master

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-push.yaml
    with:
      tag: node18
      context: node18
