name: node18

on:
  push:
    paths:
      - node18/**
    branches:
      - master
  workflow_run:
    types:
      - completed
    workflows:
      - debian
    branches:
      - master

jobs:
  build-and-push:
    uses: ./github/workflows/build-and-push.yaml@master
    with:
      tag: node18
      context: node18
