name: python3.9

on:
  push:
    paths:
      - 'python3.9/**'
      - '!python3.9/README.md'
      - '!python3.9/.dockerignore'
    branches:
      - master
  workflow_run:
    types:
      - completed
    workflows:
      - debian
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    permissions:
      contents: read
      packages: write
    with:
      tag: python3.9
      context: python3.9
