name: python3.8

on:
  push:
    paths:
      - python3.8/**
    branches:
      - master
  workflow_run:
    types:
      - completed
    workflows:
      - debian
    branches:
      - master

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      tag: python3.8
      context: python3.8
